# Generated by Django 5.1 on 2024-09-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
